language: php
sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - TRAVISCI=1

branches:
  only:
    - develop
    - master

notifications:
  email:
    - ci@andrewsville.cz

script: phpunit tests/TokenReflection