language: php

php:
  - 5.3
  - 5.4

env:
  - TRAVISCI=1

branches:
  only:
    - develop
    - master

notifications:
  email:
    - ci@andrewsville.cz

before_script:
  - composer update --dev
  
script: phpunit tests/TokenReflection
